#!/usr/bin/env node
/**
 * Pulls published PocketBase data and generates static JSON + HTML fragments.
 * Used by GitHub Actions and local builds.
 *
 * Env:
 *   POCKETBASE_URL, POCKETBASE_TOKEN, ARTIST_SLUG / ARTIST_SLUGS, OUTPUT_DIR
 */

const fs = require("fs");
const path = require("path");

const PB_URL = (process.env.POCKETBASE_URL || "").replace(/\/$/, "");
const PB_TOKEN = process.env.POCKETBASE_TOKEN || "";
const OUTPUT_DIR = process.env.OUTPUT_DIR || path.join(process.cwd(), "data");
const SLUGS = (process.env.ARTIST_SLUGS || process.env.ARTIST_SLUG || "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const RETRIES = 3;
const RETRY_DELAY_MS = 1000;

function log(level, msg) {
  const prefix = { info: "[INFO]", warn: "[WARN]", error: "[ERROR]" }[level] || "[LOG]";
  console.log(`${prefix} ${msg}`);
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function withRetry(fn) {
  let lastErr;
  for (let i = 1; i <= RETRIES; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      log("warn", `Attempt ${i}/${RETRIES} failed: ${err.message}`);
      if (i < RETRIES) await sleep(RETRY_DELAY_MS * i);
    }
  }
  throw lastErr;
}

async function pbFetch(apiPath, params = {}) {
  return withRetry(async () => {
    const url = new URL(`${PB_URL}/api${apiPath}`);
    Object.entries(params).forEach(([k, v]) => {
      if (v != null && v !== "") url.searchParams.set(k, v);
    });
    const headers = { Accept: "application/json" };
    if (PB_TOKEN) {
      headers.Authorization = PB_TOKEN.startsWith("Bearer ") ? PB_TOKEN : `Bearer ${PB_TOKEN}`;
    }
    let res;
    try {
      res = await fetch(url.toString(), { headers });
    } catch (err) {
      throw new Error(`Network error fetching ${url}: ${err.message}`);
    }
    if (!res.ok) {
      const text = await res.text();
      throw new Error(`PocketBase ${res.status} ${apiPath}: ${text.slice(0, 300)}`);
    }
    return res.json();
  });
}

async function getAllRecords(collection, filter, sort) {
  const items = [];
  let page = 1;
  let totalPages = 1;
  while (page <= totalPages) {
    const data = await pbFetch(`/collections/${collection}/records`, {
      page: String(page),
      perPage: "100",
      filter,
      sort,
    });
    items.push(...(data.items || []));
    totalPages = data.totalPages || 1;
    page += 1;
  }
  return items;
}

function fileUrl(record, field) {
  const name = record?.[field];
  if (!name) return null;
  const coll = record.collectionId || record.collectionName;
  return `${PB_URL}/api/files/${coll}/${record.id}/${name}`;
}

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(s) {
  return escapeHtml(s).replace(/'/g, "&#39;");
}

async function resolveArtist(slug) {
  const data = await pbFetch("/collections/artists/records", {
    filter: `slug = "${slug.replace(/"/g, '\\"')}"`,
    perPage: "1",
  });
  const artist = data.items?.[0];
  if (!artist) throw new Error(`Artist not found: ${slug}`);
  return artist;
}

function buildEventsHtml(events) {
  if (!events.length) return "<!-- dedalo: no published events -->\n";
  const rows = events
    .map((ev) => {
      const date = ev.date_start
        ? new Date(ev.date_start).toLocaleDateString("en-GB", {
            day: "numeric",
            month: "short",
            year: "numeric",
          })
        : "";
      const loc = [ev.venue, ev.city].filter(Boolean).join(", ");
      const ticket = ev.ticket_url
        ? ` <a href="${escapeAttr(ev.ticket_url)}" rel="noopener noreferrer">Tickets</a>`
        : "";
      return `  <li class="dedalo-event"><time datetime="${escapeAttr(ev.date_start)}">${date}</time> — <strong>${escapeHtml(ev.title)}</strong>${loc ? ` · ${escapeHtml(loc)}` : ""}${ticket}</li>`;
    })
    .join("\n");
  return `<!-- generated by dedalo-core build-static.js -->\n<ul class="dedalo-events">\n${rows}\n</ul>\n`;
}

function buildReleasesHtml(releases) {
  if (!releases.length) return "<!-- dedalo: no published releases -->\n";
  const rows = releases
    .map((rel) => {
      const date = rel.release_date
        ? new Date(rel.release_date).toLocaleDateString("en-GB", {
            year: "numeric",
            month: "short",
          })
        : "";
      const cover = rel.coverUrl
        ? `<img src="${escapeAttr(rel.coverUrl)}" alt="" width="64" height="64" loading="lazy" />`
        : "";
      const links = [rel.stream_url, rel.buy_url]
        .filter(Boolean)
        .map((u, i) => `<a href="${escapeAttr(u)}" rel="noopener noreferrer">${i === 0 ? "Listen" : "Buy"}</a>`)
        .join(" · ");
      return `  <article class="dedalo-release" id="release-${escapeAttr(rel.slug)}">${cover}<h3>${escapeHtml(rel.title)}</h3><p class="dedalo-release-date">${date}</p>${links ? `<p>${links}</p>` : ""}</article>`;
    })
    .join("\n");
  return `<!-- generated by dedalo-core build-static.js -->\n<section class="dedalo-releases">\n${rows}\n</section>\n`;
}

function buildArtistPageHtml(payload) {
  const name = escapeHtml(payload.artist.display_name || payload.artist.slug);
  const eventsBlock = buildEventsHtml(payload.events);
  const releasesBlock = buildReleasesHtml(payload.releases);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${name} — Events &amp; Releases</title>
  <meta name="generator" content="dedalo-core build-static" />
</head>
<body>
  <header><h1>${name}</h1></header>
  <main>
    <section aria-labelledby="events-heading">
      <h2 id="events-heading">Events</h2>
      ${eventsBlock}
    </section>
    <section aria-labelledby="releases-heading">
      <h2 id="releases-heading">Releases</h2>
      ${releasesBlock}
    </section>
  </main>
  <footer><p>Data generated ${escapeHtml(payload.generatedAt)}</p></footer>
</body>
</html>
`;
}

async function buildForArtist(slug) {
  log("info", `Building static output for: ${slug}`);
  const artist = await resolveArtist(slug);
  const artistId = artist.id;
  const filter = `artist = "${artistId}" && published = true`;

  const [releases, events, mixes] = await Promise.all([
    getAllRecords("releases", filter, "-release_date,sort_order"),
    getAllRecords("events", filter, "date_start"),
    getAllRecords("mixes", filter, "-published_at,sort_order"),
  ]);

  const enrich = (records, field) =>
    records.map((r) => ({
      ...r,
      ...(field ? { [`${field}Url`]: fileUrl(r, field) } : {}),
    }));

  const payload = {
    generatedAt: new Date().toISOString(),
    artist: {
      id: artist.id,
      slug: artist.slug,
      display_name: artist.display_name,
      bio: artist.bio,
      website_url: artist.website_url,
      social_links: artist.social_links,
      avatarUrl: fileUrl(artist, "avatar"),
    },
    releases: enrich(releases, "cover"),
    events: enrich(events, "flyer"),
    mixes: enrich(mixes, "cover"),
  };

  const outDir = path.join(OUTPUT_DIR, slug);
  fs.mkdirSync(outDir, { recursive: true });

  fs.writeFileSync(path.join(outDir, "site-data.json"), JSON.stringify(payload, null, 2));
  fs.writeFileSync(path.join(outDir, "events.fragment.html"), buildEventsHtml(payload.events));
  fs.writeFileSync(path.join(outDir, "releases.fragment.html"), buildReleasesHtml(payload.releases));
  fs.writeFileSync(path.join(outDir, "index.generated.html"), buildArtistPageHtml(payload));

  log(
    "info",
    `Wrote ${slug}: ${releases.length} releases, ${events.length} events, ${mixes.length} mixes`
  );
  return payload;
}

async function main() {
  if (!PB_URL) {
    log("error", "POCKETBASE_URL is required");
    process.exit(1);
  }
  if (!SLUGS.length) {
    log("error", "ARTIST_SLUG or ARTIST_SLUGS is required");
    process.exit(1);
  }

  const failures = [];
  for (const slug of SLUGS) {
    try {
      await buildForArtist(slug);
    } catch (err) {
      log("error", `${slug}: ${err.message}`);
      failures.push({ slug, error: err.message });
    }
  }

  if (failures.length) {
    log("error", `Build failed for ${failures.length} artist(s)`);
    if (process.env.GITHUB_OUTPUT) {
      fs.appendFileSync(
        process.env.GITHUB_OUTPUT,
        `build_failed=true\nfailed_slugs=${failures.map((f) => f.slug).join(",")}\n`
      );
    }
    process.exit(1);
  }

  log("info", "Build completed successfully");
}

main().catch((err) => {
  log("error", err.message);
  process.exit(1);
});